### ISSUE TITLE
Add section on visualising NeuroML models

### ISSUE THREAD

**Issue by sanjayankur31** [NeuroML/Documentation#10]
Perhaps useful for new users?

**Comment by pgleeson** [comment]
Certainly!

Probably should be broader: "Visualising contents of NML files" and contain any tool for getting a better feel for what's inside, e.g. with https://github.com/OpenSourceBrain/ACnet2/blob/master/neuroConstruct/generatedNeuroML2/MediumNet.net.nml

1) Summary Info
pynml-summary MediumNet.net.nml
```*******************************************************
* NeuroMLDocument: network_ACnet2
*
*   PulseGenerator: ['BackgroundRandomIClamps']
*
*  Network: network_ACnet2 (temperature: 6.3 degC)
*
*   60 cells in 2 populations 
*     Population: baskets_12 with 12 components of type bask
*       Locations: [(372.5585, 75.3425, 459.2106), ...]
*       Properties: color=0.0 0.19921875 0.59765625; 
*     Population: pyramidals_48 with 48 components of type pyr_4_sym
*       Locations: [(64.2564, 0.6838, 94.8305), ...]
*       Properties: color=0.796875 0.0 0.0; 
*
*   984 connections in 4 projections 
*     Projection: SmallNet_bask_bask from baskets_12 to baskets_12, synapse: GABA_syn_inh
*       60 connections: [(Connection 0: 3:0(0.41661) -> 0:0(0.68577)), ...]
*     Projection: SmallNet_bask_pyr from baskets_12 to pyramidals_48, synapse: GABA_syn
*       336 connections: [(Connection 0: 10:0(0.05824) -> 0:6(0.02628)), ...]
*     Projection: SmallNet_pyr_bask from pyramidals_48 to baskets_12, synapse: AMPA_syn_inh
*       252 connections: [(Connection 0: 1:0(0.89734) -> 0:1(0.09495)), ...]
*     Projection: SmallNet_pyr_pyr from pyramidals_48 to pyramidals_48, synapse: AMPA_syn
*       336 connections: [(Connection 0: 14:0(0.52814) -> 0:3(0.10797)), ...]
*
*   14 inputs in 1 input lists 
*     Input list: BackgroundRandomIClamps to pyramidals_48, component BackgroundRandomIClamps
*       14 inputs: [(Input 0: 37:0(0.500000)), ...]
*
*******************************************************
```

2) Generate png/svg
pynml -png MediumNet.net.nml

3) Graph of connections
pynml MediumNet.net.nml -graph 3

4) Matrix of connections
 pynml MediumNet.net.nml -matrix 0  # populations
 pynml MediumNet.net.nml -matrix 1  # individual cells

5) Povray 3D image
pynml-povray MediumNet.net.nml -scalez 8
povray Antialias=On Antialias_Depth=10 Antialias_Threshold=0.1 +W1200 +H900 MediumNet.net.nml.pov

6) Load into neuroConstruct
./nC.sh -neuroml2  MediumNet.net.nml

7) Put on OSB
(link to osb 3d net)

See also https://www.opensourcebrain.org/docs#Converting_To_NeuroML2

**Comment by sanjayankur31** [comment]
I've not added povray info yet: no commits in 2 years, and at the moment, the website can't be reached. So it may be possible that povray is no longer maintained:

https://github.com/POV-Ray/povray
