### ISSUE TITLE
Add a page on using morphology reconstructions in NeuroML

### ISSUE THREAD

**Issue by sanjayankur31** [NeuroML/Documentation#104]
Things like SWC and NeuroMorpho.

The caveat is that these reconstructions are not made with modelling in mind, so they usually have various issues that prevent them from being used "as is". So the documentation page will perhaps show an example and walk through the various issues and how these must be manually modified before they can be used in NeuroML.

If the neuroml validator etc. can show warnings/errors to help users make the necessary changes, that'll be very useful

Neuroconstruct already allows users to do all of this interactively. So the code exists.

See also https://github.com/NeuroML/pyNeuroML/issues/89

This is an important issue that will prevent experimentalists from using NeuroML, so higher priority.

**Comment by sanjayankur31** [comment]
TODO: Notebooks that walk through some examples

**Comment by sanjayankur31** [comment]
the page will have:

- general information on morphology formats
- issues with automated conversion to NeuroML for modelling
- screenshot of neuroconstruct for conversion

**Comment by pgleeson** [comment]
Morphology page added
