### ISSUE TITLE
Broken links to pdfs for minutes etc

### ISSUE THREAD

**Issue by pgleeson** [NeuroML/Documentation#129]
Some of the links to meeting reports etc. were still pointing to the old website. https://docs.neuroml.org/NeuroMLOrg/BoardMeetingReports.html#neuromlevents-meetings

These should be moved ot the new docs website, or at least changed to point here etc. https://github.com/NeuroML/NeuroMLWebsite/tree/master/public/files

**Comment by sanjayankur31** [comment]
Need to copy this page over:  https://web.archive.org/web/20220124041315/https://www.neuroml.org/workshop2012

all files are in the NeuroML website repo
