### ISSUE TITLE
Feature Request: PDF Download & Page Number

### ISSUE THREAD

**Issue by irahulsonkar** [NeuroML/Documentation#138]
1. It would be nice to have a full pdf download option for the documentation . Current download button only gives pdf of the active section/chapter.
2. Alternatively, if the user tries to build the pdf locally from the repository then there are no page numbers in the generated pdf. It will be helpful if page numbers can be included in future version for pdf.

**Comment by sanjayankur31** [comment]
Thanks for the issue @irahulsonkar . We use [jupyter-book](https://github.com/executablebooks/jupyter-book) to generate the website, so whatever is missing is missing from there. I see an issue here already:

https://github.com/executablebooks/jupyter-book/issues/1106

where this page is linked to:

https://jupyterbook.org/en/stable/advanced/pdf.html

Is this what you tried? Did you use the LaTeX way to generate the pdf or was it from the HTML? (Either way, another issue to be reported to the upstream repository if it hasn't already been reported).

**Comment by irahulsonkar** [comment]
Thanks for your reply @sanjayankur31.
Yes. I followed the same link and used pdfhtml build.

**Comment by sanjayankur31** [comment]
OK, I'll try and replicate it, and if i can it's a bug that we should file upstream.

**Comment by sanjayankur31** [comment]
You can now download the full PDF (generated with LaTeX) here:

https://docs.neuroml.org/_static/neuroml-documentation.pdf

Also added a section to the docs here:

https://docs.neuroml.org/Userdocs/Usage.html#downloading-this-documentation-as-pdf

Let me know if you find any more issues with any of this too, please. Thanks.

**Comment by irahulsonkar** [comment]
Thanks! It looks really nice.

**Comment by mrileysamc** [comment]
@sanjayankur31 , your documentation is fantastic. If you don't mind me asking: how in the world did you get the page numbers to show up in the exported PDF? I've looked through all your code and can't figure it out.

**Comment by sanjayankur31** [comment]
Hi @mrileysamc , thanks! I don't remember doing anything extra tbh---the jupyter-book pdflatex builder seems to do it automatically as part of the build. These are the only latex related builds in the config:

https://github.com/NeuroML/Documentation/blob/7685618d15161285aa6e1e66c4e2d0497fbf33d0/source/_config.yml#L17

https://github.com/NeuroML/Documentation/blob/7685618d15161285aa6e1e66c4e2d0497fbf33d0/source/_config.yml#L67

the latter is only a workaround to get citations working in captions from what I remember.

**Comment by mrileysamc** [comment]
@sanjayankur31 Thanks for the quick response! I think my problem is I'm using pdfhtml instead of pdflatex. Updating my latex package now and going to try again.
