### ISSUE TITLE
Minor typo in 'Getting Started' documentation

### ISSUE THREAD

**Issue by doorkn-b** [NeuroML/Documentation#163]
**Describe the bug**
Issue consists of a minor typo where 'an' is used in case of 'a'

In the Getting Started with Neuro-ML section, > under the 'Simulating a regular spiking Izhikevich neuron' > Down to 'Adding components to others: the add() function' > Line 2.

![typo](https://user-images.githubusercontent.com/114946929/224371522-690d5b63-0680-40ca-9eb9-1d8f5b14f388.png)

**Page on which issue is**
Which page is the issue on? ([URL](https://docs.neuroml.org/Userdocs/SingleNeuronExample.html#))

**Other relevant information**

- This is a very minor issue I'm creating to learn and contribute as a beginner. Not of much practical significance. 
- Any feedback, general or specific, would be appreciated.

- Web browser in use: Chrome
- Operating system: Windows 11

**Comment by doorkn-b** [comment]
Would be willing to create a PR or fix however necessary.

**Comment by sanjayankur31** [comment]
Thanks for the issue @doorkn-b . Yes, please feel free to open a PR :+1:
