### ISSUE TITLE
Binder not using latest main for notebooks (neither is Colab)

### ISSUE THREAD

**Issue by pgleeson** [NeuroML/Documentation#187]
Neither of these platfiorms seem to be using the latest version from main of the simple Izh example: https://docs.neuroml.org/Userdocs/NML2_examples/SingleNeuron.html. Binder doesn't recompile the docker image following a commit to main as it should, and Colab just goes straight to an older version of the notebook.

**Comment by sanjayankur31** [comment]
Maybe theyre running off master instead of main? Not sure if this is
configurable somewhere.

-- 
Thanks,

Ankur

(Sent from mobile device)

**Comment by pgleeson** [comment]
Yep, that seems to be the issue. From a quick search it's a known issue. Doesn't help that our repo was originally master then we moved to main... Simplest for now is to keep master up to date with main...

**Comment by sanjayankur31** [comment]
The automatically generated link for the binder icon specifies `master`:

https://mybinder.org/v2/gh/NeuroML/Documentation/master?urlpath=tree/source/Userdocs/NML2_examples/SingleNeuron.ipynb

Not sure if that's hard coded in the theme or if there's a configuration somewhere. Will look.

**Comment by pgleeson** [comment]
Great, thanks for finding the fix!
