### ISSUE TITLE
Add example 4: multi-compartmental single cell

### ISSUE THREAD

**Issue by sanjayankur31** [NeuroML/Documentation#19]
We'll use the OLM cell from here for this example:

https://github.com/mbezaire/ca1/blob/master/NeuroML2/

The hoc file is here: https://github.com/mbezaire/ca1/blob/master/cells/class_olmcell.hoc

**Comment by pgleeson** [comment]
@sanjayankur31 This is shaping up to a decent intro to building cells and networks from scratch: https://github.com/OpenSourceBrain/ArborShowcase/blob/main/NeuroML2/CellNetworkBuilder.ipynb. Maybe add this as a placeholder for now? It's not yet Arbor specific
