### ISSUE TITLE
Script and notebook on "A two population network of regular spiking Izhikevich neurons" failing to simulate

### ISSUE THREAD

**Issue by erik-ski** [NeuroML/Documentation#193]
**Describe the bug**
If you run the script shown in the first block of code in [A two population network of regular spiking Izhikevich neurons](https://docs.neuroml.org/Userdocs/IzhikevichNetworkExample.html), it will crash in the simulator, at line 
``` python
pynml.run_lems_with_jneuroml_neuron
```
**Page on which issue is**
Which page is the issue on? Shown above

**Other relevant information**

OS: Ubuntu 20.04
pip freeze:
```
airspeed==0.6.0
asttokens==2.4.1
attrs==23.2.0
backcall==0.2.0
blosc2==2.0.0
cachetools==5.3.3
cattrs==23.2.3
comm==0.2.1
contourpy==1.1.1
cycler==0.12.1
Cython==3.0.8
debugpy==1.8.1
decorator==5.1.1
dnspython==2.6.1
docstring-parser==0.15
exceptiongroup==1.2.0
executing==2.0.1
find-libpython==0.3.1
fonttools==4.49.0
graphviz==0.20.1
h5py==3.10.0
importlib-metadata==7.0.1
importlib_resources==6.1.2
ipykernel==6.29.3
ipython==8.12.3
jedi==0.19.1
jupyter_client==8.6.0
jupyter_core==5.7.1
kiwisolver==1.4.5
libNeuroML==0.5.7
lxml==5.1.0
matplotlib==3.7.5
matplotlib-inline==0.1.6
matplotlib-scalebar==0.8.1
modelspec==0.3.3
msgpack==1.0.7
natsort==8.4.0
nest-asyncio==1.6.0
networkx==3.1
neuromllite==0.5.9
NEURON==8.2.4
numexpr==2.8.6
numpy==1.24.4
packaging==23.2
parso==0.8.3
pexpect==4.9.0
pickleshare==0.7.5
pillow==10.2.0
pkg_resources==0.0.0
platformdirs==4.2.0
ppft==1.7.6.8
prompt-toolkit==3.0.43
psutil==5.9.8
ptyprocess==0.7.0
pure-eval==0.2.2
py-cpuinfo==9.0.0
Pygments==2.17.2
PyLEMS==0.6.7
pymongo==4.6.2
pyNeuroML==1.2.1
pyparsing==3.1.1
python-dateutil==2.9.0
PyYAML==6.0.1
pyzmq==25.1.2
six==1.16.0
stack-data==0.6.3
tables==3.8.0
tabulate==0.9.0
tornado==6.4
traitlets==5.14.1
typing_extensions==4.10.0
wcwidth==0.2.13
zipp==3.17.0
```

**Comment by sanjayankur31** [comment]
hi there, thanks for the report. It works fine for me here so it's probably something because of our different environments. For a start, could you please provide the complete error message?

Do note that to use NEURON, you must have a compiler (gcc) installed on your system since this is required to compile generated `*.mod` files for NEURON to use.

**Comment by erik-ski** [comment]
While copying the error log I saw that the NEURON_HOME variable wasn't set. I had set it before but not to where it should. 
It is now executing correctly.
I understand now that NEURON_HOME should point to the virtual environment folder.  
Is that correct?

**Comment by sanjayankur31** [comment]
It needs to point to wherever the `bin` folder containing `nrniv` and other related binaries are. An easy way of setting this is something like this (on bash):

```
export NEURON_HOME="$(dirname $(dirname $(which nrniv)))"
```

**Comment by sanjayankur31** [comment]
I'll close this now, but I've filed us a ticket to see if we can find some automated way of setting `NEURON_HOME`:

https://github.com/NeuroML/pyNeuroML/issues/308

**Comment by sanjayankur31** [comment]
@allcontributors: please add @erik-ski for bug

**Comment by erik-ski** [comment]
> It needs to point to wherever the `bin` folder containing `nrniv` and other related binaries are. An easy way of setting this is something like this (on bash):
> 
> ```
> export NEURON_HOME="$(dirname $(dirname $(which nrniv)))"
> ```

Yes, or at least explain it in the tutorials. Thank you for your time!

**Comment by sanjayankur31** [comment]
I've added this information to the docs now. Could you please take a quick look at https://github.com/NeuroML/Documentation/pull/194/ to see if that's clear enough?

**Comment by erik-ski** [comment]
Sure! I think it is clear enough. Thanks!
