### ISSUE TITLE
Docs site for nml reference has updated apparance - intended?

### ISSUE THREAD

**Issue by pgleeson** [NeuroML/Documentation#207]
Assume it's just down to an updated version of jupyter book?

![Screenshot 2024-07-01 at 10 56 01](https://github.com/NeuroML/Documentation/assets/1556687/106e8809-fc93-4047-bafe-b435c632236a)

**Comment by sanjayankur31** [comment]
Yeh, that's just new versions of jupyter book etc. Nothing we've done.
