### ISSUE TITLE
OLM.ipynb throws error for missing spike threshold definition

### ISSUE THREAD

**Issue by BKriener** [NeuroML/Documentation#209]
**Describe the bug**
I wanted to test, if my local installation of pyneuroml works, so tried some examples. When running the OLM example it returned 
ValueError: Validation failed:
- MembraneProperties: Number of values for spike_threshes is below the minimum allowed, expected at least 1, found 0
I got the same error when running the notebook on Colab.

**Page on which issue is**
https://docs.neuroml.org/Userdocs/NML2_examples/OLM.html

**Other relevant information**
- Web browser in use: firefox
- Operating system: fedora

**Comment by sanjayankur31** [comment]
Thanks for the report @BKriener. I expect this is a fallout from the change in the schema--SpikeThreshold is now compulsory. I'll update this example now.

**Comment by BKriener** [comment]
Suspected something along the lines, thanks!
