### ISSUE TITLE
Right hand TOC does not scroll (and goes out of page)

### ISSUE THREAD

**Issue by sanjayankur31** [NeuroML/Documentation#21]
The right hand TOC does not scroll, goes out of the page, and covers the right nav button on long pages, like the schemas.

**Comment by sanjayankur31** [comment]
Reported upstream: https://github.com/executablebooks/jupyter-book/issues/1245

**Comment by sanjayankur31** [comment]
@pgleeson said:

One option might be to put all the base Types together under a single heading and use sub headings for anything base* etc. Would help keep the right column cleaner. People would normally be more interested in top level/instantiable elements and only go to base* if drilling down from top level.

**Comment by pgleeson** [comment]
Oops...

**Comment by sanjayankur31** [comment]
Seems to be fixed now on live. Please update your virtual env. Closing.
