### ISSUE TITLE
Status of C++ API and Matlab toolbox?

### ISSUE THREAD

**Issue by sanjayankur31** [NeuroML/Documentation#28]
Are these usable/stable/maintained? They haven't seen commits in the last few years from the looks of it. 

If these are not actively maintained, we shouldn't put them in the same place as the other supported tools since we don't want users using these (and then opening issues/asking questions that we won't be able to help with). A separate page for "other tools" or "tools under development" would work best perhaps?

**Comment by pgleeson** [comment]
Both were left in an installable/usable state, and should still be. Inactivity is partly down to no application using them as libraries currently (that I know of). 
Need to be tried out again to check that the instructions are still ok. They still should fulfill their intended scope: this can serve as an API for reading/writing NeuroML in that language, and so no reason the should be promoted.

**Comment by sanjayankur31** [comment]
Sounds good. I'll update their docs etc. like the other projects.
