### ISSUE TITLE
Check images and text on  funding page (and add any missing ones)

### ISSUE THREAD

**Issue by sanjayankur31** [NeuroML/Documentation#32]
This page:

https://neuroml.github.io/Documentation/NeuroMLOrg/Funding.html

Source: https://github.com/NeuroML/Documentation/edit/master/source/NeuroMLOrg/Funding.md

**Comment by pgleeson** [comment]
Pinging @Angus-Silver. Any missing funders? 

Note @sanjayankur31 Wellcome logo should be updated and "Trust" removed.

**Comment by sanjayankur31** [comment]
Fixed the text. What would the new logo to use be? Should I just get it off the website or do they provide one we are meant to use?

**Comment by pgleeson** [comment]
You could just use the images here: https://github.com/OpenSourceBrain/redmine/tree/master/public/images
