### ISSUE TITLE
Migrate https://neuroml.org/specifications to https://neuroml.github.io/Documentation/Userdocs/NeuroMLv1.html

### ISSUE THREAD

**Issue by sanjayankur31** [NeuroML/Documentation#33]
Copy over the contents.

**Comment by sanjayankur31** [comment]
@pgleeson : just noticed that *all* the links on the page are broken, so I cant get the v1 XSD files from here either. Would you have a copy of the XSD files that I could archive here in the docs repo by any chance? (I couldn't find them in either the NeuroML2 or the NeuroMLWebsite repos).

**Comment by pgleeson** [comment]
They're all here: https://github.com/NeuroML/org.neuroml1.model/tree/master/src/main/resources/NeuroML1Schemas.

The original source for these (from back in the day) is here: https://sourceforge.net/p/neuroml/code/HEAD/tree/trunk/web/NeuroMLFiles/Schemata/v1.8.1/

**Comment by sanjayankur31** [comment]
Thanks. I'll link to the GitHub files then.
