### ISSUE TITLE
NeuroMLv2 and LEMS page needs review

### ISSUE THREAD

**Issue by sanjayankur31** [NeuroML/Documentation#45]
https://docs.neuroml.org/Userdocs/NeuroMLv2.html needs review.

**Comment by sanjayankur31** [comment]
@borismarin : would you have a minute to go through this bit please? (just to check that I've copied over bits correctly and that it all makes sense etc.? :smiley:

**Comment by borismarin** [comment]
It seemed easier to directly submit a PR with suggestions... https://github.com/NeuroML/Documentation/pull/101
