### ISSUE TITLE
Create page on "defining new ComponentTypes using LEMS"

### ISSUE THREAD

**Issue by sanjayankur31** [NeuroML/Documentation#46]
We had a few questions about writing new mechanisms etc. in LEMS, so  a page on this would be useful.

**Comment by pgleeson** [comment]
A script for building LEMS with Python: https://github.com/LEMS/pylems/blob/master/examples/apitest2.py
Defining a completely new (non neuro) type in XML: https://github.com/NeuroML/NeuroMLlite/blob/master/examples/test_files/Lorenz1963.xml
Defining a new synapse in LEMS: https://github.com/OpenSourceBrain/BonoClopath2017/blob/master/NeuroML2/AMPA_NMDA.synapse.nml
Defining a new LEMS channel (or more specificly a gate ina  channel): https://github.com/OpenSourceBrain/SmithEtAl2013-L23DendriticSpikes/blob/master/NeuroML2/na.channel.nml
Defining a new calcium pool (concentrationModel) in LEMS: https://github.com/OpenSourceBrain/PospischilEtAl2008/blob/master/NeuroML2/channels/Ca/Ca.nml

Need an example of creating a LEMS type in Python, but building on the baseCell, baseSynapse, etc.
