### ISSUE TITLE
Add information on "Sharing NeuroML models"

### ISSUE THREAD

**Issue by sanjayankur31** [NeuroML/Documentation#47]
Since NeuroML is about re-use, a page listing how people can share NeuroML models would be nice:

- neuroml-db.org
- OSB
- modeldb
- ...?

Or perhaps we add this all to the "finding NeuroML models" page?

https://docs.neuroml.org/Userdocs/FindingNeuroMLModels.html

@pgleeson : what do you think?

**Comment by scrook** [comment]
I think both on the same page. Here's where to find them but should also be sharing them.

**Comment by pgleeson** [comment]
Yes, maybe rename the page: Finding/sharing NeuroML models?

@scrook Do you have a nce screenshot for neuroml-db for that page?
