### ISSUE TITLE
Extract & show documention string from parameters/exposures etc.

### ISSUE THREAD

**Issue by pgleeson** [NeuroML/Documentation#56]
Synapses has a few of these:
https://github.com/NeuroML/NeuroML2/blob/master/NeuroML2CoreTypes/Synapses.xml#L86

**Comment by sanjayankur31** [comment]
The pylems parser does not pick up descriptions for paramters. Opened PR: 

https://github.com/LEMS/pylems/pull/46

Will generate these from my virtualenv in the meantime until a new pylems release is made.
