### ISSUE TITLE
Usage blurb on izhikevich notebook page

### ISSUE THREAD

**Issue by pgleeson** [NeuroML/Documentation#84]
Users may be completely new to running notebooks, so the first nb example in the docs should have some standalone instructions for complete novices.

It would be good to have some brief intro text on https://docs.neuroml.org/Userdocs/NML2_examples/SingleNeuron.html, which explains:
- This is a Python notebook embedded in the NeuroML documentation
- You can view a previously run copy of the notebook below or run this yourself in your browser on Binder or Collab by selecting the rocket.
- You may have to wait for a minute or two for it to launch
- On Binder, try pressing the double arrow for ...
- On Collab select...

**Comment by sanjayankur31** [comment]
I think adding a separate page on "how to use this documentation" is probably better than adding information on notebooks to one example---what if someone skips it and goes to the third one, for instance?

**Comment by pgleeson** [comment]
Sure, that's probably better. A page speciifically on using the notebooks via the nml docs can have screenshots, a step by step guide etc. and maybe be linked to from each of the current notebooks.
